import axios from 'axios';
const client=axios.create({baseURL:import.meta.env.VITE_API_URL||'http://127.0.0.1:8000/api/v1',timeout:10000,headers:{'Content-Type':'application/json'}});
client.interceptors.response.use(r=>r,err=>Promise.reject(err));
export const getHealth=()=>client.get('/health').then(r=>r.data);
export const getProfile=()=>client.get('/profile').then(r=>r.data);
export const getStats=()=>client.get('/stats').then(r=>r.data);
export const getConversations=()=>client.get('/conversations').then(r=>r.data);
export const getCustomers=()=>client.get('/customers').then(r=>r.data);
export const getCustomerSummary=()=>client.get('/customers/summary').then(r=>r.data);
export const getOrders=()=>client.get('/orders').then(r=>r.data);
export const getFollowups=()=>client.get('/followups').then(r=>r.data);
export const getInvoices=()=>client.get('/invoices').then(r=>r.data);
export const getPayments=()=>client.get('/payments').then(r=>r.data);
export const getAnalytics=()=>client.get('/analytics/summary').then(r=>r.data);
export const getEvaluation=()=>client.get('/evaluation').then(r=>r.data);
export const completeFollowup=(id)=>client.post(`/followups/${id}/complete`).then(r=>r.data);
export const ingest=(payload)=>client.post('/conversations',payload).then(r=>r.data);
export const askNexora=(question)=>client.post('/ask-nexora',{question}).then(r=>r.data);
export const runEvaluation=()=>client.post('/evaluation/run').then(r=>r.data);
export default client;
