from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm

def make_invoice_pdf(order,customer,items,number,seller):
    buf=BytesIO(); doc=SimpleDocTemplate(buf,pagesize=A4,rightMargin=16*mm,leftMargin=16*mm,topMargin=14*mm,bottomMargin=14*mm); st=getSampleStyleSheet(); story=[Paragraph(seller['name'],st['Title']),Paragraph(f'GSTIN: {seller["gstin"]}',st['Normal']),Spacer(1,8),Paragraph(f'<b>Tax Invoice</b> — {number}',st['Heading2']),Paragraph(f'Buyer: {customer.name} | {customer.phone or ""}',st['Normal']),Spacer(1,10)]
    data=[['Item','Qty','Rate','GST','Amount']]
    for x in items: data.append([x.product.name,str(x.quantity),f'₹{float(x.unit_price):.2f}',f'{x.tax_rate:g}%',f'₹{float(x.unit_price)*x.quantity:.2f}'])
    data += [['','','','Tax',f'₹{float(order.tax):.2f}'],['','','','Total',f'₹{float(order.total):.2f}']]
    t=Table(data,colWidths=[72*mm,18*mm,25*mm,20*mm,28*mm]); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#151c2b')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.4,colors.lightgrey),('ALIGN',(1,1),(-1,-1),'RIGHT'),('FONTNAME',(0,-2),(-1,-1),'Helvetica-Bold'),('BACKGROUND',(0,-2),(-1,-1),colors.HexColor('#eef1f7'))])); story.append(t); story += [Spacer(1,16),Paragraph('This is a simulated GST invoice generated by Nexora for demonstration purposes.',st['Italic'])]; doc.build(story); buf.seek(0); return buf
