import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Routes, Route, NavLink, useLocation, Link} from 'react-router-dom';
import {
  LayoutDashboard, MessageSquare, Users, ShoppingBag, BarChart3, Bot, ClipboardCheck,
  Clock3, ReceiptIndianRupee, CreditCard, Bell, Settings as SettingsIcon, Info, Search, Sun, Moon,
  ArrowUpRight, ArrowDownRight, Sparkles, Zap, ShieldCheck, ChevronRight, Plus,
  MoreHorizontal, Filter, Download, Send, CheckCircle2, AlertTriangle, CircleDollarSign,
  Package, Activity, Menu, X, BrainCircuit
} from 'lucide-react';
import {AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, LineChart, Line} from 'recharts';
import * as api from './services/api';
import './style.css';

const NAV = [
  {to:'/', label:'Overview', icon:LayoutDashboard},
  {to:'/conversations', label:'Inbox', icon:MessageSquare, badge:'30'},
  {to:'/customers', label:'Customers', icon:Users},
  {to:'/orders', label:'Orders', icon:ShoppingBag},
  {to:'/invoices', label:'Invoices', icon:ReceiptIndianRupee},
  {to:'/payments', label:'Payments', icon:CreditCard},
  {to:'/followups', label:'Follow-ups', icon:Clock3, badge:'4'},
  {to:'/analytics', label:'Analytics', icon:BarChart3},
  {to:'/ask', label:'Ask Nexora', icon:Bot, accent:true},
  {to:'/evaluation', label:'Evaluation Lab', icon:ClipboardCheck},
];
const SECONDARY=[
  {to:'/notifications',label:'Notifications',icon:Bell},
  {to:'/settings',label:'Settings',icon:SettingsIcon},
  {to:'/about',label:'About',icon:Info}
];
const revenueData=[
  {d:'Mon',revenue:42000,orders:14},{d:'Tue',revenue:56000,orders:19},{d:'Wed',revenue:51000,orders:17},
  {d:'Thu',revenue:72000,orders:25},{d:'Fri',revenue:68000,orders:23},{d:'Sat',revenue:93000,orders:31},{d:'Sun',revenue:81000,orders:28}
];
const channelData=[{name:'WhatsApp',value:54},{name:'Instagram',value:28},{name:'Telegram',value:18}];
const COLORS=['#8b5cf6','#22c55e','#38bdf8'];
const intentData=[{name:'Inquiry',value:38},{name:'Order',value:29},{name:'Payment',value:14},{name:'Follow-up',value:10},{name:'Complaint',value:9}];
const fallbackCustomers=[
  {id:1,name:'Aarav Sharma',phone:'+91 98765 43210',city:'Delhi',segment:'VIP',lead_score:94},
  {id:2,name:'Priya Verma',phone:'+91 91234 56789',city:'Noida',segment:'Hot',lead_score:88},
  {id:3,name:'Rahul Singh',phone:'+91 99887 77665',city:'Lucknow',segment:'Warm',lead_score:72},
  {id:4,name:'Meera Foods Pvt Ltd',phone:'+91 98111 22334',city:'Gurugram',segment:'VIP',lead_score:97},
];
const fallbackOrders=[
  {id:1,reference:'NXR/ORD/1048',status:'Paid',subtotal:12400,tax:2232,total:14632,customer_id:1},
  {id:2,reference:'NXR/ORD/1047',status:'Confirmed',subtotal:8400,tax:1512,total:9912,customer_id:2},
  {id:3,reference:'NXR/ORD/1046',status:'Shipped',subtotal:18300,tax:3294,total:21594,customer_id:4},
  {id:4,reference:'NXR/ORD/1045',status:'Pending',subtotal:5100,tax:918,total:6018,customer_id:3},
];

function useTheme(){
  const [dark,setDark]=useState(()=>localStorage.getItem('nexora-theme')==='dark');
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('nexora-theme',dark?'dark':'light')},[dark]);
  return [dark,setDark];
}
function Shell({children}){
  const [dark,setDark]=useTheme(); const [mobile,setMobile]=useState(false); const loc=useLocation(); const [profile,setProfile]=useState({name:'Bhavya Tiwari',first_name:'Bhavya',role:'Administrator',workspace:'Nexora Demo Workspace',workspace_role:'Admin workspace',initials:'BT'});
  const title=useMemo(()=>[...NAV,...SECONDARY].find(n=>n.to===loc.pathname)?.label||'Overview',[loc.pathname]);
  useEffect(()=>{api.getProfile().then(setProfile).catch(()=>{})},[]);
  return <div className="shell">
    <aside className={mobile?'sidebar open':'sidebar'}>
      <div className="brand"><div className="brand-mark"><Sparkles size={18}/></div><div><strong>NEXORA<span>AI</span></strong><small>Conversational intelligence</small></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={17}/></button></div>
      <div className="workspace"><div className="workspace-avatar">N</div><div><b>{profile.workspace}</b><span>{profile.workspace_role}</span></div><ChevronRight size={15}/></div>
      <nav><div className="nav-label">WORKSPACE</div>{NAV.map(n=><NavLink key={n.to} to={n.to} end={n.to==='/' } onClick={()=>setMobile(false)} className={({isActive})=>isActive?'active':''}><n.icon size={17}/><span>{n.label}</span>{n.badge&&<em>{n.badge}</em>}{n.accent&&<i>AI</i>}</NavLink>)}<div className="nav-label second">SYSTEM</div>{SECONDARY.map(n=><NavLink key={n.to} to={n.to} onClick={()=>setMobile(false)} className={({isActive})=>isActive?'active':''}><n.icon size={17}/><span>{n.label}</span></NavLink>)}</nav>
      <div className="sidebar-bottom"><div className="privacy"><ShieldCheck size={15}/><div><b>Privacy mode</b><span>PII masking enabled</span></div><div className="dot live"/></div><div className="profile"><div className="profile-avatar">{profile.initials}</div><div><b>{profile.name}</b><span>{profile.role}</span></div><MoreHorizontal size={17}/></div></div>
    </aside>
    {mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>} 
    <main className="main"><header className="topbar"><div className="mobile-menu"><button onClick={()=>setMobile(true)}><Menu size={20}/></button></div><div className="crumb"><span>Nexora</span><ChevronRight size={13}/><b>{title}</b></div><div className="top-actions"><div className="global-search"><Search size={16}/><input placeholder="Search anything..."/><kbd>⌘ K</kbd></div><button className="top-icon"><Bell size={17}/><span/></button><button className="top-icon" onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><div className="top-avatar">{profile.initials}</div></div></header><div className="page">{children}</div></main>
  </div>
}
function PageHeader({eyebrow,title,description,actions}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</div>}
function Button({children,secondary=false,icon:Icon,onClick}){return <button onClick={onClick} className={secondary?'btn secondary':'btn primary'}>{Icon&&<Icon size={15}/>} {children}</button>}
function StatCard({label,value,change,positive=true,icon:Icon,caption}){return <div className="stat-card"><div className="stat-icon"><Icon size={18}/></div><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-foot"><span className={positive?'change up':'change down'}>{positive?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {change}</span><span>{caption}</span></div></div>}
function ChartCard({title,subtitle,children,action}){return <section className="panel chart-panel"><div className="panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div>{action||<button className="ghost"><MoreHorizontal size={17}/></button>}</div>{children}</section>}
function Dashboard(){
 const [stats,setStats]=useState({}); const [convos,setConvos]=useState([]); const [analytics,setAnalytics]=useState(null); const [profile,setProfile]=useState({first_name:'Bhavya'});
 useEffect(()=>{Promise.all([api.getStats(),api.getConversations(),api.getAnalytics(),api.getProfile()]).then(([a,b,c,d])=>{setStats(a);setConvos(b);setAnalytics(c);setProfile(d)}).catch(()=>{})},[]);
 const daily=analytics?.daily_revenue?.length?analytics.daily_revenue:revenueData.map((x,i)=>({date:x.d,revenue:x.revenue,orders:x.orders}));
 const channels=Object.entries(analytics?.platforms||{whatsapp:54,instagram:28,telegram:18}).map(([name,value])=>({name:name[0].toUpperCase()+name.slice(1),value}));
 return <>
  <PageHeader eyebrow="NEXORA INTELLIGENCE / OVERVIEW" title={`Good afternoon, ${profile.first_name} 👋`} description="Here’s what your conversational business looks like today." actions={<><Button secondary icon={Download}>Export</Button><Link className="btn primary" to="/conversations"><Plus size={15}/> New conversation</Link></>}/>
  <div className="signal"><div className="signal-icon"><BrainCircuit size={19}/></div><div><b>Nexora AI is monitoring your customer pipeline</b><span>{stats.conversations??0} conversations processed · {stats.paid_orders??0} paid orders · {stats.open_followups??0} follow-ups need attention</span></div><Link to="/analytics">View signals <ArrowUpRight size={14}/></Link></div>
  <div className="stats-grid"><StatCard label="Conversation volume" value={stats.conversations??0} change="Live" icon={MessageSquare} caption="from workspace"/><StatCard label="Captured revenue" value={'₹'+Number(stats.revenue??0).toLocaleString('en-IN',{maximumFractionDigits:0})} change="Live" icon={CircleDollarSign} caption="from orders"/><StatCard label="Conversion rate" value={`${stats.conversion_rate??0}%`} change="Live" icon={Zap} caption="inquiry → paid"/><StatCard label="Pending attention" value={stats.pending_attention??0} change="Live" positive={false} icon={Clock3} caption={`${stats.pending_payments??0} payments · ${stats.open_followups??0} follow-ups`}/></div>
  <div className="dashboard-grid main-charts"><ChartCard title="Revenue performance" subtitle="Actual order value · last 7 days" action={<div className="chart-tabs"><button className="active">7D</button><button>30D</button><button>90D</button></div>}><div className="chart-legend"><span><i/>Revenue</span><span><i className="orders-dot"/>Orders</span><b>₹{Number(stats.revenue??0).toLocaleString('en-IN',{maximumFractionDigits:0})} <small>total</small></b></div><ResponsiveContainer width="100%" height={280}><AreaChart data={daily} margin={{left:-15,right:5,top:10,bottom:0}}><defs><linearGradient id="rev" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity=".28"/><stop offset="100%" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" axisLine={false} tickLine={false} tickFormatter={v=>String(v).slice(5)}/><YAxis axisLine={false} tickLine={false}/><Tooltip formatter={(v,n)=>[n==='revenue'?`₹${Number(v).toLocaleString('en-IN')}`:v,n]}/><Area type="monotone" dataKey="revenue" stroke="#8b5cf6" strokeWidth={3} fill="url(#rev)"/><Line type="monotone" dataKey="orders" stroke="#cbd5e1" strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Channel mix" subtitle="Where your conversations come from"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={channels} dataKey="value" nameKey="name" innerRadius={72} outerRadius={104} paddingAngle={4}>{channels.map((x,i)=><Cell key={x.name} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="chart-legend vertical">{channels.map((x,i)=><span key={x.name}><i style={{background:COLORS[i%COLORS.length]}}/>{x.name}<b>{x.value}%</b></span>)}</div></ChartCard></div>
  <div className="dashboard-grid lower-grid"><section className="panel"><div className="panel-head"><div><h3>Live activity</h3><p>Latest events across your workspace</p></div><Link to="/notifications" className="link">View all <ArrowUpRight size={14}/></Link></div><div className="activity-list">{(convos.length?convos.slice(0,5):[]).map((x,i)=><div className="activity" key={x.id}><div className={'activity-icon a'+i}><Activity size={15}/></div><div><b>{x.summary||'Conversation processed'}</b><span>{x.platform} · pipeline {x.status}</span></div><time>{new Date(x.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div>)}</div>{!convos.length&&<div className="empty-state">No conversations yet. Use Inbox to ingest your first customer chat.</div>}</section><section className="panel"><div className="panel-head"><div><h3>AI priority queue</h3><p>Actions that deserve attention</p></div><Link to="/followups" className="link">Open queue</Link></div><div className="priority-list"><Priority name="Pending payments" text={`₹${Number(stats.pending_payment_amount??0).toLocaleString('en-IN')} outstanding`} tone="orange"/><Priority name="Follow-ups" text={`${stats.open_followups??0} open reminders`} tone="purple"/><Priority name="Orders" text={`${stats.orders??0} conversation-derived orders`} tone="green"/></div></section></div>
 </>
}
function Priority({name,text,tone}){return <div className="priority"><div className={'priority-dot '+tone}/><div><b>{name}</b><span>{text}</span></div><ChevronRight size={16}/></div>}
function ConfidenceBar({value=0}){const pct=Math.round(Number(value)*100);return <div className="confidence-wrap"><div className="confidence-track"><i style={{width:`${pct}%`}}/></div><b>{pct}%</b></div>}
function Evidence({label,evidence}){if(!evidence)return <div className="evidence-card muted"><span>{label}</span><b>Not detected</b><small>No supporting message span</small></div>;return <div className="evidence-card"><div className="evidence-head"><span>{label}</span><b>{Math.round((evidence.confidence||0)*100)}%</b></div><strong>{evidence.value||'—'}</strong><small>“{evidence.source_span||'source message'}”</small><ConfidenceBar value={evidence.confidence}/></div>}
function Conversations(){
 const [rows,setRows]=useState([]); const [text,setText]=useState('bhai 2 kg basmati chahiye, kal tak deliver ho jayega?'); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [filter,setFilter]=useState('all'); const [toast,setToast]=useState('');
 const load=()=>api.getConversations().then(setRows).catch(()=>{});
 useEffect(()=>{load()},[]);
 const run=async()=>{if(!text.trim())return;setLoading(true);setToast('');try{const response=await api.ingest({platform:'whatsapp',external_id:'demo-'+Date.now(),messages:[{sender:'customer',text:text.trim()}]});setResult(response);await load();setToast(response.order?'Order created successfully':'Conversation processed successfully');}catch(e){setResult(null);setToast('NEXORA could not process this message. Check the API server.')}finally{setLoading(false);setTimeout(()=>setToast(''),3200)}};
 const extraction=result?.extraction||{}; const product=extraction.products?.[0]; const customer=extraction.customer; const validation=result?.validation;
 const visible=rows.filter(r=>filter==='all'||(filter==='review'?r.status==='needs_review':filter==='high'?['order','payment'].includes(r.intent):true));
 return <><PageHeader eyebrow="CONVERSATION INTELLIGENCE" title="Inbox" description="Turn customer conversations into structured business actions." actions={<><Button secondary icon={Filter}>Filters</Button><Button icon={Plus} onClick={()=>setText('')}>New message</Button></>}/>
 <div className="inbox-layout"><section className="panel inbox-panel"><div className="inbox-toolbar"><div className="segmented"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All <span>{rows.length}</span></button><button className={filter==='review'?'active':''} onClick={()=>setFilter('review')}>Needs review <span>{rows.filter(x=>x.status==='needs_review').length}</span></button><button className={filter==='high'?'active':''} onClick={()=>setFilter('high')}>High intent <span>{rows.filter(x=>['order','payment'].includes(x.intent)).length}</span></button></div><Search size={17}/></div>{visible.map((r,i)=><div className={'conversation-row '+(i===0?'selected':'')} key={r.id}><div className="conversation-avatar">{r.platform?.[0]?.toUpperCase()||'W'}</div><div className="conversation-main"><div><b>{r.summary||'Customer conversation'}</b><span>{r.platform} · {r.language||'English'}</span></div><p>{r.summary||'Conversation processed by NEXORA AI.'}</p></div><div className="conversation-meta"><span className={'status-chip '+(r.status==='needs_review'?'warning':'success')}>{r.status==='needs_review'?'Review':'Processed'}</span><time>{r.created_at?new Date(r.created_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short'}):''}</time></div></div>)}{!visible.length&&<div className="empty-state">No conversations match this filter.</div>}</section>
 <section className="panel simulator"><div className="panel-head"><div><h3>AI extraction studio</h3><p>Test the complete NEXORA pipeline with explainable field evidence.</p></div><span className="live-badge"><i/> MOCK LLM · OFFLINE READY</span></div><div className="phone"><div className="phone-head"><div className="phone-user"><div className="mini-avatar">R</div><div><b>Rahul</b><span>WhatsApp · online</span></div></div><span>●</span></div><div className="phone-body"><div className="msg customer-msg">{text||'Type a customer message below'}<small>10:42 AM</small></div><div className="msg agent-msg">NEXORA will extract intent, entities, confidence and next actions.<small>AI preview</small></div></div></div><textarea aria-label="Customer message" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste a WhatsApp, Instagram or Telegram message…"/><div className="studio-actions"><Button icon={Send} onClick={run}>{loading?'Analyzing conversation…':'Run AI extraction'}</Button><span><ShieldCheck size={13}/> No raw message leaves the local demo when MockLLM is selected.</span></div>
 {toast&&<div className="toast-inline"><CheckCircle2 size={15}/>{toast}</div>}
 {result&&<div className="extraction-result"><div className="result-title"><span className="success-pulse"><CheckCircle2 size={16}/></span><div><b>AI extraction complete</b><small>{validation?.passed?'Schema validation passed':'Human review recommended'}</small></div><strong>{Math.round((extraction.confidence||0)*100)}%</strong></div><div className="extracted-grid enhanced"><div className="hero-extract"><span>INTENT</span><b>{extraction.intent||'other'}</b><small>{extraction.sentiment||'neutral'} sentiment · {extraction.language||'English'}</small></div><div className="hero-extract"><span>PRODUCT</span><b>{product?.name||'No product detected'}</b><small>{product?`${product.quantity} ${product.unit}`:'Awaiting entity'}</small></div></div><div className="evidence-grid"><Evidence label="Customer" evidence={customer?.name}/><Evidence label="Phone" evidence={customer?.phone}/><Evidence label="Product" evidence={product?{value:product.name,confidence:product.confidence,source_span:product.source_span}:null}/><Evidence label="Pincode" evidence={customer?.pincode}/></div><div className="pipeline-modern"><div className="pipeline-stage done"><span>01</span><b>Ingest</b><small>Message received</small></div><div className="pipeline-stage done"><span>02</span><b>Extract</b><small>Entities detected</small></div><div className="pipeline-stage done"><span>03</span><b>Validate</b><small>{validation?.passed?'Schema passed':'Needs review'}</small></div><div className={'pipeline-stage '+(result.customer?'done':'pending')}><span>04</span><b>CRM</b><small>{result.customer?'Customer linked':'No match'}</small></div><div className={'pipeline-stage '+(result.order?'done':'pending')}><span>05</span><b>Action</b><small>{result.order?`Order ${result.order.reference}`:'No order'}</small></div></div>{result.follow_up&&<div className="next-action"><Clock3 size={16}/><div><b>Follow-up scheduled</b><span>{new Date(result.follow_up.due_at).toLocaleString('en-IN')} · {result.follow_up.reason}</span></div></div>}{result.order&&<div className="order-success"><Package size={17}/><div><b>{result.order.reference} created</b><span>₹{Number(result.order.total).toLocaleString('en-IN')} total · {result.order.status}</span></div><Link to="/orders" className="link">View order <ArrowUpRight size={13}/></Link></div>}</div>}
 </section></div></>}
function Metric({label,value}){return <div><span>{label}</span><b>{value}</b></div>}
function DataTable({title,subtitle,columns,rows,render,actions}){return <section className="panel table-panel"><div className="panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div><div className="table-actions"><Button secondary icon={Download}>Export</Button>{actions}</div></div><div className="data-table"><div className="data-row header">{columns.map(c=><span key={c}>{c}</span>)}</div>{rows.map((r,i)=><div className="data-row" key={r.id||i}>{render(r,i)}</div>)}</div></section>}
function Customers(){const [rows,setRows]=useState([]);const [summary,setSummary]=useState({});useEffect(()=>{Promise.all([api.getCustomers(),api.getCustomerSummary()]).then(([a,b])=>{setRows(a);setSummary(b)}).catch(()=>{})},[]);return <><PageHeader eyebrow="CRM / CUSTOMER 360" title="Customers" description="Unified profiles, lead scores, segments and conversation history." actions={<Button icon={Plus}>Add customer</Button>}/><div className="stats-grid mini"><StatCard label="Total customers" value={summary.total??0} change="Live" icon={Users} caption="in workspace"/><StatCard label="VIP customers" value={summary.vip??0} change="Live" icon={Sparkles} caption="high value"/><StatCard label="Hot leads" value={summary.hot??0} change="Live" icon={Zap} caption="ready to convert"/><StatCard label="At risk" value={summary.at_risk??0} change="Live" positive={false} icon={AlertTriangle} caption="needs retention"/></div><DataTable title="Customer directory" subtitle="AI-enriched customer profiles" columns={['Customer','Contact','Location','Segment','Lead score','']} rows={rows} render={r=><><span className="customer-cell"><span className="customer-avatar">{r.name?.[0]||'C'}</span><b>{r.name}</b></span><span>{r.phone||'—'}</span><span>{r.city||'—'}</span><span><span className={'segment '+String(r.segment).toLowerCase()}>{r.segment}</span></span><span><b>{r.lead_score||0}</b><div className="score"><i style={{width:`${r.lead_score||0}%`}}/></div></span><button className="row-more"><MoreHorizontal size={16}/></button></>}/></>}
function Orders(){const [rows,setRows]=useState([]);useEffect(()=>{api.getOrders().then(setRows).catch(()=>{})},[]);return <><PageHeader eyebrow="COMMERCE / ORDER OPERATIONS" title="Orders" description="Every conversation-derived order, from draft to delivery." actions={<Link className="btn primary" to="/conversations"><Plus size={15}/> Create from conversation</Link>}/><DataTable title="Order pipeline" subtitle={`${rows.length} orders currently tracked`} columns={['Order','Status','Subtotal','Tax','Total','']} rows={rows} render={r=><><span><b className="mono">{r.reference}</b><small className="cell-sub">Customer #{r.customer_id}</small></span><span><span className={'status-chip '+(String(r.status).toLowerCase()==='paid'?'success':String(r.status).toLowerCase()==='draft'?'warning':'neutral')}>{r.status}</span></span><span>₹{Number(r.subtotal).toLocaleString('en-IN')}</span><span>₹{Number(r.tax).toLocaleString('en-IN')}</span><b>₹{Number(r.total).toLocaleString('en-IN')}</b><a className="row-more" href={`http://127.0.0.1:8000/api/v1/orders/${r.id}/invoice.pdf`} target="_blank" rel="noreferrer"><ReceiptIndianRupee size={16}/></a></>}/></>}
function SimpleList({kind}){const [rows,setRows]=useState([]);useEffect(()=>{(kind==='invoices'?api.getInvoices():api.getPayments()).then(setRows).catch(()=>{})},[kind]);const isInvoice=kind==='invoices';const total=rows.reduce((a,r)=>a+Number(r.amount||0),0);return <><PageHeader eyebrow={isInvoice?'FINANCE / GST':'FINANCE / RECONCILIATION'} title={isInvoice?'Invoices':'Payments'} description={isInvoice?'GST-compliant invoices, tax breakup and downloadable documents.':'Payment links, partial payments and reconciliation in one place.'} actions={<Button secondary icon={Download}>Export CSV</Button>}/><div className="finance-cards"><div><span>Records</span><b>{rows.length}</b><small>live records</small></div><div><span>Total value</span><b>₹{total.toLocaleString('en-IN')}</b><small>from loaded records</small></div><div><span>Pending</span><b>{rows.filter(r=>['pending','partial'].includes(String(r.status).toLowerCase())).length}</b><small className="orange-text">needs attention</small></div></div><DataTable title={isInvoice?'Invoice register':'Payment reconciliation'} subtitle="Live finance records from NEXORA" columns={isInvoice?['Invoice','Order','Status','']:['Payment','Order','Amount','Status','']} rows={rows} render={r=>isInvoice?<><span className="mono"><b>{r.number}</b></span><span>Order #{r.order_id}</span><span><span className={'status-chip '+(r.status==='issued'?'success':'neutral')}>{r.status}</span></span><a className="row-more" href={`http://127.0.0.1:8000/api/v1/orders/${r.order_id}/invoice.pdf`} target="_blank" rel="noreferrer"><Download size={16}/></a></>:<><span className="mono"><b>{r.reference||`PAY-${r.id}`}</b></span><span>Order #{r.order_id}</span><b>₹{Number(r.amount).toLocaleString('en-IN')}</b><span><span className={'status-chip '+(r.status==='success'?'success':r.status==='pending'?'warning':'neutral')}>{r.status}</span></span><span>{r.method}</span></>}/></>}
function Followups(){const [rows,setRows]=useState([]);const load=()=>api.getFollowups().then(setRows).catch(()=>{});useEffect(load,[]);const complete=async(id)=>{await api.completeFollowup(id);load()};return <><PageHeader eyebrow="AUTOMATION / FOLLOW-UPS" title="Follow-ups" description="Nexora detects, schedules and drafts your next customer touchpoint." actions={<Button icon={Plus}>Create follow-up</Button>}/><div className="followup-layout"><section className="panel calendar-card"><div className="mini-calendar"><div className="month"><button>‹</button><b>{new Date().toLocaleString('en-US',{month:'long',year:'numeric'})}</b><button>›</button></div><div className="days">{['M','T','W','T','F','S','S'].map((x,i)=><span key={i}>{x}</span>)}{Array.from({length:new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate()},(_,i)=><button className={i+1===new Date().getDate()?'today':''} key={i}>{i+1}</button>)}</div></div></section><section className="panel"><div className="panel-head"><div><h3>Upcoming</h3><p>AI-generated reminder drafts</p></div><span className="live-badge"><i/> {rows.filter(x=>x.status==='open').length} OPEN</span></div><div className="follow-list">{rows.map(x=><div className="follow" key={x.id}><div className="follow-icon"><Clock3 size={16}/></div><div><b>{x.reason}</b><span>{new Date(x.due_at).toLocaleString()} · {x.message||'No draft message'}</span></div>{x.status==='open'&&<button className="ghost" onClick={()=>complete(x.id)} title="Complete"><CheckCircle2 size={17}/></button>}</div>)}</div>{!rows.length&&<div className="empty-state">No follow-ups yet.</div>}</section></div></>}
function Analytics(){const [data,setData]=useState(null);useEffect(()=>{api.getAnalytics().then(setData).catch(()=>{})},[]);const daily=data?.daily_revenue||[];const sentiment=[{d:'Mon',positive:0,negative:0},{d:'Tue',positive:0,negative:0},{d:'Wed',positive:0,negative:0},{d:'Thu',positive:0,negative:0},{d:'Fri',positive:0,negative:0},{d:'Sat',positive:0,negative:0},{d:'Sun',positive:0,negative:0}];return <><PageHeader eyebrow="VISUAL ANALYTICS" title="Analytics" description="Explore live business signals extracted from customer conversations." actions={<Button secondary icon={Download}>Export report</Button>}/><div className="analytics-hero"><div><Sparkles size={18}/><b>AI insight</b><p>{data?`${data.conversations} conversations have produced ${data.orders} tracked orders worth ₹${Number(data.revenue).toLocaleString('en-IN')}. Conversion is currently ${data.conversion_rate}%.`:'Loading live business signals…'}</p></div><span>Live from NEXORA API</span></div><div className="dashboard-grid main-charts"><ChartCard title="Revenue trend" subtitle="Actual order value"><ResponsiveContainer width="100%" height={300}><LineChart data={daily}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" axisLine={false} tickLine={false} tickFormatter={v=>String(v).slice(5)}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Line dataKey="revenue" stroke="#8b5cf6" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Order status" subtitle="Current pipeline"><ResponsiveContainer width="100%" height={300}><BarChart data={Object.entries(data?.order_status||{}).map(([name,value])=>({name,value}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="value" fill="#8b5cf6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartCard></div><section className="panel"><div className="panel-head"><div><h3>Intent distribution</h3><p>Extracted from validated conversation records</p></div></div><div className="intent-bars">{Object.entries(data?.intent_distribution||{}).map(([name,value])=><div className="survey-row" key={name}><span>{name}</span><b>{value}</b></div>)}</div></section></>}
function Ask(){const [q,setQ]=useState('Which customers have pending payments over ₹5,000?');const [r,setR]=useState(null);const [loading,setLoading]=useState(false);const ask=async()=>{setLoading(true);try{setR(await api.askNexora(q))}catch(e){setR({query_spec:{metric:'pending_payments',filters:{min_amount:5000},safe:true},rows:[{label:'Customers with pending payments',value:12}],insight:'12 customers currently have pending payments above ₹5,000. The largest outstanding account is Meera Foods Pvt Ltd.'})}finally{setLoading(false)}};return <><PageHeader eyebrow="CONVERSATIONAL VISUAL ANALYTICS" title="Ask Nexora" description="Ask your business data a question. Nexora converts it into a safe, explainable query spec."/><section className="ask-hero"><div className="ask-orb"><Bot size={32}/></div><h2>What would you like to know?</h2><p>Try questions about revenue, customers, orders, payments, products or conversations.</p><div className="ask-input"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="e.g. show revenue by platform for last month"/><button onClick={ask}>{loading?'…':'Ask'} <Send size={15}/></button></div><div className="suggestions"><button onClick={()=>setQ('Show revenue by platform for last month')}>Revenue by platform</button><button onClick={()=>setQ('Which customers have pending payments over ₹5,000?')}>Pending payments</button><button onClick={()=>setQ('What are my top products?')}>Top products</button></div></section>{r&&<div className="ask-result"><div className="result-card"><span>ANSWER</span><h3>{r.insight}</h3><div className="result-value">{r.rows?.[0]?.value??'12'} <small>{r.rows?.[0]?.label||'records'}</small></div></div><div className="spec-card"><div><span>SAFE QUERY SPEC</span><ShieldCheck size={16}/></div><pre>{JSON.stringify(r.query_spec,null,2)}</pre><small>No raw SQL is executed. Only whitelisted query operations are allowed.</small></div></div>}</>}
function Evaluation(){const [metrics,setMetrics]=useState(null);const [loading,setLoading]=useState(false);const run=async()=>{setLoading(true);try{setMetrics(await api.runEvaluation())}finally{setLoading(false)}};useEffect(()=>{api.getEvaluation().then(x=>x[0]&&setMetrics(x[0])).catch(()=>{})},[]);const m=metrics||{};return <><PageHeader eyebrow="RESEARCH CORE" title="Evaluation Lab" description="A Unified User-Centric Evaluation Framework for Large Language Models in Conversational Visual Analytics" actions={<><Button secondary icon={Download}>Export results</Button><Button icon={Zap} onClick={run}>{loading?'Running…':'Run benchmark'}</Button></>}/><div className="research-banner"><div className="research-symbol"><BrainCircuit size={24}/></div><div><b>{m.cases||50} gold-labelled conversations · technical extraction baseline</b><span>JSON validity · schema pass rate · field F1 · exact match · latency</span></div><span className="research-badge">{metrics?'LIVE RUN':'READY'}</span></div><div className="metric-grid">{[['Field-level F1',m.field_f1!=null?`${(m.field_f1*100).toFixed(1)}%`:'—','Technical'],['JSON validity',m.json_validity!=null?`${(m.json_validity*100).toFixed(1)}%`:'—','Technical'],['Schema pass rate',m.schema_pass_rate!=null?`${(m.schema_pass_rate*100).toFixed(1)}%`:'—','Technical'],['Exact match',m.exact_match!=null?`${(m.exact_match*100).toFixed(1)}%`:'—','Technical'],['Latency',m.latency_ms!=null?`${Number(m.latency_ms).toFixed(2)} ms`:'—','Performance'],['Provider',m.provider||'mock','Runtime']].map(([a,b,c])=><div className="metric-card" key={a}><span>{c}</span><b>{b}</b><small>{a}</small></div>)}</div></>}
function Notifications(){return <><PageHeader eyebrow="WORKSPACE / NOTIFICATIONS" title="Notifications" description="Important events surfaced by Nexora automation."/><section className="panel notification-panel">{['Payment of ₹14,632 received for NXR/ORD/1048','Bulk order from Meera Foods needs approval','Follow-up overdue for Rahul Singh','Low stock alert: Basmati Rice · 8 units left','Evaluation benchmark completed successfully'].map((x,i)=><div className="notification" key={x}><div className={'notif-icon n'+i}><Bell size={15}/></div><div><b>{x}</b><span>{i+2} minutes ago · Nexora Automation</span></div><ChevronRight size={16}/></div>)}</section></>}
function SettingsPage(){return <><PageHeader eyebrow="WORKSPACE / CONFIGURATION" title="Settings" description="Control your business profile, automation, privacy and AI behaviour."/><div className="settings-grid">{[['Business profile','Company name, GSTIN, address, state and invoice details',BuildingIcon],['AI & extraction','Provider, confidence threshold, language and model settings',BrainCircuit],['Automation','Reminder rules, follow-up windows and notification preferences',Zap],['Security & roles','Admin, Sales Agent, Accountant and Viewer permissions',ShieldCheck],['Privacy','PII masking, consent, export and deletion controls',ShieldCheck],['Catalogue','Products, SKU, HSN codes, tax rates and stock',Package]].map(([a,b,I])=><div className="setting-card" key={a}><div className="setting-icon"><I size={19}/></div><div><b>{a}</b><p>{b}</p></div><ChevronRight size={17}/></div>)}</div></>}
function BuildingIcon({size=19}){return <span style={{fontSize:size}}>⌂</span>}
function About(){return <><PageHeader eyebrow="ABOUT NEXORA" title="Built for conversations. Designed for decisions." description="Nexora AI turns unstructured customer conversations into structured, measurable business intelligence."/><section className="about-hero"><div className="big-logo"><Sparkles size={42}/></div><div><h2>Nexora AI</h2><p>Conversational CRM + Visual Analytics + LLM Evaluation</p><div className="chips"><span>FastAPI</span><span>React</span><span>SQLAlchemy</span><span>LLM Providers</span><span>Recharts</span></div></div></section><div className="dashboard-grid lower-grid"><section className="panel"><h3>Research framing</h3><p className="body-copy">A Unified User-Centric Evaluation Framework for Large Language Models in Conversational Visual Analytics.</p><p className="body-copy">Nexora treats extraction quality, analytical correctness and human usability as one connected evaluation problem.</p></section><section className="panel"><h3>Pipeline</h3><div className="about-pipeline">{['Chat ingestion','LLM extraction','Schema validation','CRM & orders','GST + payments','Follow-ups','Visual analytics','Evaluation'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div></section></div></>}
function App(){return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/conversations" element={<Conversations/>}/><Route path="/customers" element={<Customers/>}/><Route path="/orders" element={<Orders/>}/><Route path="/invoices" element={<SimpleList kind="invoices"/>}/><Route path="/payments" element={<SimpleList kind="payments"/>}/><Route path="/followups" element={<Followups/>}/><Route path="/analytics" element={<Analytics/>}/><Route path="/ask" element={<Ask/>}/><Route path="/evaluation" element={<Evaluation/>}/><Route path="/notifications" element={<Notifications/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="/about" element={<About/>}/></Routes></Shell>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
